name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nebularg/actions-luacheck@d4137dd840545b28521ed21931e06913d93c0bc1 # v1
        with:
          args: --no-color
      - name: Install LuaJIT
        run: sudo apt-get update && sudo apt-get install -y luajit
      - name: Unit tests
        run: luajit tests/test_addon.lua
